"""Client construction and generator-drift helpers for the Nokia NaC SDK.

The SDK under `network_as_code` is generated by Fern from the CAMARA OpenAPI specs.
Two consequences shape this module:

* Versioned endpoints appear under two possible Python spellings — the Fern method
  name (`verify_v1`) and the generator's snake_case rendering (`verify_v_1`). The
  published reference disagrees with itself on which one ships. `resolve` picks
  whichever the installed package actually exposes instead of guessing.
* Generated request models set `extra="allow"`, so polymorphic CAMARA subtypes
  (notably the CIRCLE area, whose `center` and `radius` are not declared on the
  base schema) are passed through as plain dicts.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Callable

REPO_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = Path(__file__).resolve().parent / ".env"


class MissingCredentials(RuntimeError):
    """Raised when NAC_API_KEY is absent — probes report this, they do not crash."""


def load_env() -> None:
    """Load nac/.env if python-dotenv is present. Real environment always wins."""
    try:
        from dotenv import load_dotenv
    except ImportError:
        return
    if ENV_PATH.exists():
        load_dotenv(ENV_PATH, override=False)


def api_key() -> str:
    load_env()
    key = os.environ.get("NAC_API_KEY", "").strip()
    if not key:
        raise MissingCredentials(
            "NAC_API_KEY is not set. Copy nac/.env.example to nac/.env and fill it in."
        )
    return key


def msisdns() -> list[str]:
    """Simulator numbers, in declaration order. First is the airframe."""
    load_env()
    raw = os.environ.get("NAC_MSISDNS", "")
    return [n.strip() for n in raw.split(",") if n.strip()]


def webhook_base() -> str:
    load_env()
    return os.environ.get("NAC_WEBHOOK_BASE", "").strip()


def build():
    """Return a configured NetworkAsCodeApi client."""
    from network_as_code import NetworkAsCodeApi, NetworkAsCodeApiEnvironment

    return NetworkAsCodeApi(
        api_key=api_key(),
        environment=NetworkAsCodeApiEnvironment.DEFAULT,
    )


def resolve(namespace: Any, *candidates: str) -> Callable[..., Any]:
    """Return the first method the installed SDK actually exposes.

    Guards against Fern's inconsistent rendering of versioned endpoint names.
    """
    for name in candidates:
        method = getattr(namespace, name, None)
        if callable(method):
            return method
    available = sorted(n for n in dir(namespace) if not n.startswith("_"))
    raise AttributeError(
        f"none of {candidates} exist on {type(namespace).__name__}; "
        f"available: {', '.join(available)}"
    )


def to_jsonable(value: Any) -> Any:
    """Best-effort serialisation of SDK pydantic models into evidence JSON."""
    if isinstance(value, list):
        return [to_jsonable(v) for v in value]
    if isinstance(value, dict):
        return {k: to_jsonable(v) for k, v in value.items()}
    dump = getattr(value, "model_dump", None)
    if callable(dump):
        return dump(mode="json", by_alias=True)
    return value
