#!/usr/bin/env python3
"""Clip a base map for the monitored window: towns, water, provincial borders.

    python nabd/data/extract_basemap.py <dir with Natural Earth geojson>

A lattice of squares is not a map. What makes a reader place the footprint in
the world is the ordinary furniture of a map — the towns it covers, the water it
runs around, the provincial line it crosses — so this pulls exactly that much
from Natural Earth and nothing more, clipped to the window and thinned to what a
100 km map can resolve.

Natural Earth is public domain (https://www.naturalearthdata.com), which is the
reason it is used here rather than a tile service: the console has to stay one
file that opens with no network, and a base map that needs a CDN would break the
one property that makes the demonstration safe to run in a room.

Expects these in the given directory:
    cities1000.txt                 (GeoNames)
    ne_10m_lakes.geojson
    ne_10m_rivers_lake_centerlines.geojson
    ne_10m_admin_1_states_provinces.geojson
    ne_10m_roads.geojson
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "basemap.json"
GEO = HERE / "shakemap-us6000jllz-geo.json"

MIN_STEP_DEG = 0.004  # ~400 m


def bounds() -> tuple[float, float, float, float]:
    b = json.loads(GEO.read_text(encoding="utf-8"))["bounds"]
    return b["lat_min"], b["lat_max"], b["lon_min"], b["lon_max"]


def inside(lon: float, lat: float, box) -> bool:
    lat0, lat1, lon0, lon1 = box
    return lat0 <= lat <= lat1 and lon0 <= lon <= lon1


def thin(points):
    out = []
    for lon, lat, *_ in points:
        if not out or abs(lon - out[-1][0]) + abs(lat - out[-1][1]) >= MIN_STEP_DEG:
            out.append([round(lon, 4), round(lat, 4)])
    return out


def rings(geom):
    """Every ring or line in a geometry, whatever its type."""
    t, c = geom["type"], geom["coordinates"]
    if t == "LineString":
        return [c]
    if t in ("MultiLineString", "Polygon"):
        return list(c)
    if t == "MultiPolygon":
        return [ring for poly in c for ring in poly]
    return []


def clip_lines(features, box, keep=lambda p: True):
    out = []
    for f in features:
        if not keep(f.get("properties", {})):
            continue
        for ring in rings(f["geometry"]):
            run = []
            for point in ring:
                if inside(point[0], point[1], box):
                    run.append(point)
                elif len(run) > 1:
                    out.append(thin(run))
                    run = []
                else:
                    run = []
            if len(run) > 1:
                out.append(thin(run))
    return [r for r in out if len(r) > 1]


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    src = Path(argv[1])
    box = bounds()
    lat0, lat1, lon0, lon1 = box

    def load(name):
        return json.loads((src / f"{name}.geojson").read_text(encoding="utf-8"))["features"]

    # Natural Earth's 10m places layer carries two cities for a window this size.
    # GeoNames carries the district towns, which is what makes it read as a place
    # rather than a rectangle. CC BY 4.0, credited in `source` below.
    towns = []
    for line in (src / "cities1000.txt").read_text(encoding="utf-8").splitlines():
        f = line.split("	")
        if len(f) < 15:
            continue
        lat, lon = float(f[4]), float(f[5])
        if not inside(lon, lat, box):
            continue
        towns.append({
            "name": f[1],
            "lon": round(lon, 4), "lat": round(lat, 4),
            "pop": int(f[14] or 0),
            "rank": {"PPLA": 1, "PPLA2": 2, "PPLA3": 3}.get(f[7], 4),
        })
    towns.sort(key=lambda t: (t["rank"], -t["pop"]))
    towns = towns[:28]  # enough to place the eye, few enough to read

    payload = {
        "_": "Base map for the monitored window. Generated by nabd/data/extract_basemap.py.",
        "source": {
            "shapes": "Natural Earth 10m (public domain, naturalearthdata.com) — "
                      "lakes, rivers, admin-1 boundaries, roads",
            "places": "GeoNames cities1000 (CC BY 4.0, geonames.org)",
            "retrieved": date.today().isoformat(),
        },
        "bounds": {"lat_min": lat0, "lat_max": lat1, "lon_min": lon0, "lon_max": lon1},
        "towns": towns,
        "lakes": clip_lines(load("ne_10m_lakes"), box),
        "rivers": clip_lines(load("ne_10m_rivers_lake_centerlines"), box),
        "borders": clip_lines(load("ne_10m_admin_1_states_provinces"), box),
        # Only the trunk network: minor roads at this scale are texture, not information.
        "roads": clip_lines(
            load("ne_10m_roads"), box,
            keep=lambda p: (p.get("type") or "").lower() in
            ("major highway", "beltway", "secondary highway", "road"),
        ),
    }
    OUT.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(towns)} towns, {len(payload['lakes'])} lake ring(s), "
          f"{len(payload['rivers'])} river(s), {len(payload['borders'])} border run(s), "
          f"{len(payload['roads'])} road run(s), {OUT.stat().st_size // 1024} KB")
    for t in towns[:12]:
        print(f"    {t['name']:<22} {t['pop']:>9,}  {t['lat']}N {t['lon']}E")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
