#!/usr/bin/env python3
"""Clip a street-level base map for the city-scale scenes.

    python nabd/data/extract_city.py osm-city.json

Four of the five scenes watch a 6.7 km square over Kahramanmaraş. Natural Earth
carries two roads and one dot at that scale, which is not a map — it is a dark
rectangle with squares on it. OpenStreetMap carries the streets, the water and
the neighbourhood names, and that is what makes the city-scale scenes legible.

Source: OpenStreetMap contributors, via the Overpass API. ODbL; credited in the
extract and in the console's footer.

Kept small enough to inline in a file that must open with no network:
coordinates are stored as integers in ten-thousandths of a degree (about 11 m),
delta-encoded along each way, which is roughly a quarter of the size of the
plain decimals and costs nothing to decode.
"""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "basemap-city.json"

SCALE = 10000  # ten-thousandths of a degree, ~11 m
MIN_STEP = 5   # in those units, ~55 m: finer than a 15 km map can show

MAJOR = {"motorway", "trunk", "primary", "secondary"}
MINOR = {"tertiary", "unclassified"}
LOCAL = {"residential"}


def encode(points: list[tuple[float, float]]) -> list[int] | None:
    """Delta-encoded [lon0, lat0, dlon, dlat, ...] in SCALE units."""
    out: list[int] = []
    last: tuple[int, int] | None = None
    for lon, lat in points:
        x, y = round(lon * SCALE), round(lat * SCALE)
        if last is None:
            out += [x, y]
            last = (x, y)
        elif abs(x - last[0]) + abs(y - last[1]) >= MIN_STEP:
            out += [x - last[0], y - last[1]]
            last = (x, y)
    return out if len(out) >= 4 else None


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    elements = json.loads(Path(argv[1]).read_text(encoding="utf-8"))["elements"]

    roads: dict[str, list] = {"major": [], "minor": [], "local": []}
    water: list = []
    streams: list = []
    rail: list = []
    places: list = []

    for e in elements:
        tags = e.get("tags", {})
        if e["type"] == "node":
            kind = tags.get("place")
            name = tags.get("name")
            if not name or kind not in ("city", "town", "village", "suburb", "neighbourhood"):
                continue
            places.append({
                "name": name, "lon": round(e["lon"], 4), "lat": round(e["lat"], 4),
                "rank": {"city": 1, "town": 2, "village": 3, "suburb": 4}.get(kind, 5),
            })
            continue
        geom = [(p["lon"], p["lat"]) for p in e.get("geometry", [])]
        if len(geom) < 2:
            continue
        line = encode(geom)
        if line is None:
            continue
        highway = tags.get("highway")
        if highway in MAJOR:
            roads["major"].append(line)
        elif highway in MINOR:
            roads["minor"].append(line)
        elif highway in LOCAL:
            roads["local"].append(line)
        elif tags.get("natural") == "water" or tags.get("landuse") in ("reservoir", "basin"):
            water.append(line)
        elif tags.get("waterway") in ("river", "stream"):
            streams.append(line)
        elif tags.get("railway") == "rail":
            rail.append(line)

    places.sort(key=lambda p: (p["rank"], p["name"]))
    places = [p for p in places if p["rank"] <= 2] + [p for p in places if p["rank"] > 2][:22]

    payload = {
        "_": "Street-level base map for the city-scale scenes. Coordinates are delta-encoded "
             "integers in 1e-4 degrees. Generated by nabd/data/extract_city.py.",
        "source": {
            "data": "OpenStreetMap contributors (ODbL), via the Overpass API",
            "retrieved": date.today().isoformat(),
        },
        "scale": SCALE,
        "roads": roads,
        "water": water,
        "streams": streams,
        "rail": rail,
        "places": places,
    }
    OUT.write_text(json.dumps(payload, separators=(",", ":"), ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(roads['major'])} major / {len(roads['minor'])} minor / "
          f"{len(roads['local'])} local roads, {len(water)} water, {len(streams)} stream(s), "
          f"{len(rail)} rail, {len(places)} places, {OUT.stat().st_size // 1024} KB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
